version: '3'
services:
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        command: mysqld --sql_mode="" --default_authentication_plugin=mysql_native_password
        restart: always
        security_opt:
            - seccomp:unconfined
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "13306:3306"
        volumes:
            - "./data/mysql:/var/lib/mysql"
            - "./apps/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
    postgresdb:
        image: pgrouting/pgrouting:${PG_VERSION}
        container_name: ${PG_NAME}
        env_file:
            - ".env"
        environment:
            POSTGRES_PASSWORD: ${PG_PASSWORD}
        ports:
            - '15432:5432'
        volumes:
            - "./data/postgresql/data:/var/lib/postgresql/data"
    web:
        image: nginx:alpine
        container_name: ${NGINX_NAME}
        volumes:
            #- "./apps/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./apps/ssl:/etc/ssl"
            - "./html:/var/www/html"
            - "./apps/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
            #- "./datafile:/opt/datafile"
        ports:
            - "180:80"
            - "181:81"
            - "182:82"
            - "1443:443"
        stdin_open: true
        tty: true
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        container_name: ${PHP_NAME}
        restart: always
        volumes:
            - "./apps/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./html:/var/www/html"
